import Layout from '@/components/Layout'
import Head from 'next/head'
import porfilepic from "../../public/images/profile/developer-pic-1.png"
import Image from 'next/image'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import Hireme from '@/components/Hireme'
import bulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
import Pagetransition from '@/components/Pagetransition'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Pagetransition/>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
          <div className="flex items-center justify-between w-full">
            <div className='w-1/2'>
              <Image src={porfilepic} alt='codepro' className='w-full h-auto
  ' />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>

              <AnimatedText text="Turning Vision Into Reality With Code And Design." className='!text-6xl !text-left' />
              <p className='my-4 text-base font-medium'>As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications.
                Explore my latest projects and articles, showcasing my expertise in React.js and web development.
              </p>
              <div className='flex w-full items-center self-center mt-2 '>
                <Link className='flex items-center bg-black text-light font-semibold p-2.5 px-6 rounded-lg text-lg hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark' href="/Resumemain2.pdf" target={"_blank"} download={true}>
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link href="mailto:mdtarikhan007@gmail.com" target={"_blank"}
                  className='ml-4 text-lg font-medium text-dark capitalize underline'
                >Contact</Link>
              </div>
            </div>

          </div>
        </Layout>
<Hireme/>
<div className='absolute right-8 bottom-8 w-24 inline-block '>
  <Image src={bulb} alt='light bulb' className='w-full h-auto '></Image>
</div>
      </main>
    </>
  )
}
