import Layout from "@/components/Layout";
import Head from "next/head";
import porfilepic from "../../public/images/profile/developer-pic-1.png";
import Image from "next/image";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import Hireme from "@/components/Hireme";
import bulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import Pagetransition from "@/components/Pagetransition";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Pagetransition />
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="!pt-16 md:!pt-0 ">
          <div className="flex items-center justify-between w-full flex-col lg:flex-row">
            <div className="w-full md:w-1/2">
              {/* img */}
              <Image
                src={porfilepic}
                alt="codepro"
                className="w-full h-auto  md:inline-block md:flex-col"
                priority
                sizes="(max-width:768px) 100vw, (max-width:1200px) 50vw , 50vw"
              />
            </div>
            <div className="w-full flex flex-col items-center self-center lg:text-center lg:w-1/2">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Design."
                className=" !text-center  !text-3xl  sm:!text-5xl md:!text-left md:!text-6xl "
              />
              <p className="my-4 text-center text-xs md:text-base font-medium sm:text-sm md:text-left">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
              <div className="flex w-full items-center self-center mt-2 sm:self-center justify-center md:justify-start ">
                <Link
                  className="flex items-center bg-black text-light  p-2 px-4 text-base   rounded-lg  hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark font-semibold md:p-2.5 md:px-6 md:text-lg "
                  href="/tarikhg_resume.pdf"
                  target={"_blank"}
                  download={true}
                >
                  Resume <LinkArrow className={"w-4 ml-1 md:w-6"} />
                </Link>
                <Link
                  href="mailto:mdtarikhan007@gmail.com"
                  target={"_blank"}
                  className="ml-4 text-base font-medium text-dark capitalize underline md:text-lg"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <Hireme />
        <div className="absolute hidden right-8 bottom-8 w-24 md:inline-block">
          <Image src={bulb} alt="light bulb" className="w-full h-auto "></Image>
        </div>
      </main>
    </>
  );
}
